In [2]:
import numpy as np

### 산술 연산
- 배열은 기본적으로 요소의 연산이 가능

리스트의 덧셈

In [4]:
list1 = [1,2,3]
list2 = [4.5,6]
print(list1+list2)

[1, 2, 3, 4.5, 6]


배열의 덧셈

In [5]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1+arr2)

[5 7 9]


- shape이 같은 배열은 연산 가능 

모양이 같은 배열 연산

In [39]:
arr1 = np.arange(1,7,dtype=np.float32).reshape(2,3)
arr2 = np.arange(11,17,dtype=np.float32).reshape(2,3)
print(arr1+arr2)  # 더하기
print(arr2-arr1)  # 빼기

[[12. 14. 16.]
 [18. 20. 22.]]
[[10. 10. 10.]
 [10. 10. 10.]]


In [40]:
print(arr1*arr2)   # 곱하기
print(arr2/arr1)   # 나누기
print(arr1**arr2)  # 제곱


[[11. 24. 39.]
 [56. 75. 96.]]
[[11.         6.         4.3333335]
 [ 3.5        3.         2.6666667]]
[[1.0000000e+00 4.0960000e+03 1.5943230e+06]
 [2.6843546e+08 3.0517578e+10 2.8211098e+12]]


In [41]:
print(arr2//arr1)  # 몫
print(arr2%arr1)  # 나머지

[[11.  6.  4.]
 [ 3.  3.  2.]]
[[0. 0. 1.]
 [2. 0. 4.]]


- Numpy의 연산함수

np.add(arr1, arr2)

In [9]:
print(arr1+arr2)
print(np.add(arr1,arr2))

[[12. 14. 16.]
 [18. 20. 22.]]
[[12. 14. 16.]
 [18. 20. 22.]]


np.subtract(arr1, arr2)

In [10]:
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[-10. -10. -10.]
 [-10. -10. -10.]]
[[-10. -10. -10.]
 [-10. -10. -10.]]


np.multiply(arr1, arr2)

In [11]:
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[11. 24. 39.]
 [56. 75. 96.]]
[[11. 24. 39.]
 [56. 75. 96.]]


np.divide(arr1, arr2)

In [12]:
print(arr1/arr2)
print(np.divide(arr1,arr2))

[[0.09090909 0.16666667 0.23076923]
 [0.2857143  0.33333334 0.375     ]]
[[0.09090909 0.16666667 0.23076923]
 [0.2857143  0.33333334 0.375     ]]


- broadcasting
- 연산하고자 하는 배열의 모양이 다른 경우의 연산

일반적인 상황

In [13]:
arr3 = np.arange(10).reshape(5,2)
arr4 = np.arange(10).reshape(2,5)
print(arr3+arr4)

# operands could not be broadcast together with shapes (5,2) (2,5) : (5,2) (2,5) shape이 다름

ValueError: operands could not be broadcast together with shapes (5,2) (2,5) 

- Broadcasting : shape이 다른 배열 간 연산 지원

배열과 스칼라의 연산

In [14]:
scalar = 10
vector = np.array([1,2,3])
print(scalar+vector)

[11 12 13]


In [15]:
scalar = 10
matrix = np.array([[1,2,3],[4,5,6]])
print(scalar+matrix)

[[11 12 13]
 [14 15 16]]


In [17]:
scalar = 10
tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(scalar+tensor)

[[[11 12 13]
  [14 15 16]]

 [[17 18 19]
  [20 21 22]]

 [[23 24 25]
  [26 27 28]]]


벡터와 매트릭스의 연산

In [24]:
matirix = np.arange(1,10).reshape(3,3)
vector = np.arange(11,14).reshape(1,3)
print(matrix+vector)

[[12 14 16]
 [15 17 19]
 [18 20 22]]


In [25]:
matrix = np.arange(1,10).reshape(3,3)
vector = np.arange(11,14).reshape(3,1)
print(matrix+vector)

[[12 13 14]
 [16 17 18]
 [20 21 22]]


벡터와 벡터의 브로드캐스팅 연산

In [27]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3]).reshape(3,1)
print(arr1)
print(arr2)

print(arr1+arr2)

[1 2 3]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


행렬 연산
-  수학에서의 행렬의 곱셈
- np.dot(arr1, arr2) 함수 사용

일반적인 행렬곱

In [28]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])

print(arr1*arr2)


[1 4 9]


np.dot 사용 행렬곱

In [30]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3]).T

print(np.dot(arr1,arr2))

14


np.dot(arr1,arr2)

In [31]:
print(np.dot(arr1,arr2))

14


arr1.dot(arr2)

In [32]:
print(arr1.dot(arr2))

14


arr1@arr2

In [33]:
print(arr1@arr2)

14


2차원 배열 행렬곱

In [44]:
arr3 = np.arange(1,7).reshape(2,3)
arr4 = np.arange(11,17).reshape(3,2)

print(np.dot(arr3,arr4))

[[ 82  88]
 [199 214]]
