In [2]:
import numpy as np

### 파일 처리
- ndarray의 정보를 파일로 저장할 수 있다.
- 일반적인 파일 확장자는 npy를 사용한다.

파일 저장(tofile)

In [3]:
n = np.random.randn(3,5)
print(n)
n.tofile('n.npy')

[[-0.13668569 -0.70078759  0.57526571  0.21907485  1.72530128]
 [ 1.12893078  0.16578261 -0.39925898  0.61451696  0.95427301]
 [-0.94834851  0.26403572  0.4059866   2.32584331 -1.13295394]]


파일 불러오기(fromfile)

In [4]:
m = np.fromfile('C:/Study/Study Python2/n.npy')
print(m)

[-0.13668569 -0.70078759  0.57526571  0.21907485  1.72530128  1.12893078
  0.16578261 -0.39925898  0.61451696  0.95427301 -0.94834851  0.26403572
  0.4059866   2.32584331 -1.13295394]


파일저장, 불러오기(np.save, np.load)

In [5]:
np.save('n1.npy',n)
m1 = np.load('n1.npy')
print(m1)

[[-0.13668569 -0.70078759  0.57526571  0.21907485  1.72530128]
 [ 1.12893078  0.16578261 -0.39925898  0.61451696  0.95427301]
 [-0.94834851  0.26403572  0.4059866   2.32584331 -1.13295394]]


In [ ]:
# n.tofile > n.npy
# np.load('n.npy')
# np.load('n.npy') # 안 열린다.


주의해야할점..