In [1]:
import numpy as np

### 파일 처리
- ndarray의 정보를 파일로 저장할 수 있다.
- 일반적인 파일 확장자는 npy를 사용한다.

파일 저장(tofile)

In [3]:
n = np.random.randn(3,5)
print(n)
n.tofile('n.npy')

[[-0.3866583   1.21179749  0.7507118   1.44030856 -2.62523251]
 [-1.41617307  0.23836438  0.91137456  0.20390135  0.03598366]
 [-0.03596328  0.82681176  0.8684979   1.38714746  1.33071803]]


파일 불러오기(fromfile)

In [4]:
m = np.fromfile('C:/Study/Study Python2/n.npy')
print(m)

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Study/Study Python2/n.npy'

파일저장, 불러오기(np.save, np.load)

In [5]:
np.save('n1.npy',n)
m1 = np.load('n1.npy')
print(m1)

[[-0.3866583   1.21179749  0.7507118   1.44030856 -2.62523251]
 [-1.41617307  0.23836438  0.91137456  0.20390135  0.03598366]
 [-0.03596328  0.82681176  0.8684979   1.38714746  1.33071803]]


In [ ]:
# n.tofile > n.npy
# np.load('n.npy')
# np.load('n.npy') # 안 열린다.


주의해야할점..

txt 파일 저장(np.savetxt)

np.savetxt('n.txt',n)

In [6]:
np.savetxt('n.txt',n)

txt 파일 불러오기(np.loadtxt)

In [7]:
np.loadtxt('n.txt')

array([[-0.3866583 ,  1.21179749,  0.7507118 ,  1.44030856, -2.62523251],
       [-1.41617307,  0.23836438,  0.91137456,  0.20390135,  0.03598366],
       [-0.03596328,  0.82681176,  0.8684979 ,  1.38714746,  1.33071803]])

csv 파일 저장, 불러오기

In [8]:
np.savetxt('n.csv',n) # 확장자만 csv로 바꾸면 됨

csv 파일 불러오기

In [11]:
np.loadtxt('n.csv')

array([[-0.3866583 ,  1.21179749,  0.7507118 ,  1.44030856, -2.62523251],
       [-1.41617307,  0.23836438,  0.91137456,  0.20390135,  0.03598366],
       [-0.03596328,  0.82681176,  0.8684979 ,  1.38714746,  1.33071803]])

파일 저장 및 불러오기

In [15]:
np.savetxt('n.csv',n, delimiter=    ',')

In [18]:
np.loadtxt('n.csv', delimiter=',', dtype=str)

array([['-3.866583044010725723e-01', '1.211797493936002557e+00',
        '7.507117995619452255e-01', '1.440308556188018230e+00',
        '-2.625232509314221474e+00'],
       ['-1.416173074955638711e+00', '2.383643809267564362e-01',
        '9.113745552097094471e-01', '2.039013534049234078e-01',
        '3.598365774128516742e-02'],
       ['-3.596328367283348898e-02', '8.268117556103287136e-01',
        '8.684979045730202296e-01', '1.387147456548070368e+00',
        '1.330718034117179149e+00']], dtype='<U25')

[문제1]
1~25 범위의 5x5 2차원 행렬을 생성하고 구분자(delimiter)는 ,(콤마)로 지정해서 data.csv에 저장해봅시다

In [30]:
n = np.arange(1,26).reshape(5,5)
print(n)
np.savetxt('data.csv',n,delimiter=    ',')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


[문제2]
06_data1.txt 파일을 읽어와서 dtype = str으로 변수 arr1에 저장하고 출력해 봅시다.

In [27]:
arr1 = np.loadtxt('C:/Study/Study_Python2/data/06_data1.txt', dtype=str)
arr1

array([['1', '15', '14', '4'],
       ['12', '6', '7', '9'],
       ['8', '10', '11', '5'],
       ['13', '3', '2', '16']], dtype='<U2')

In [31]:
arr3 = np.loadtxt('C:/Study/Study_Python2/data/06_data1.txt', delimiter='\t' ,dtype=str)
arr3

array([['1', '15', '14', '4'],
       ['12', '6', '7', '9'],
       ['8', '10', '11', '5'],
       ['13', '3', '2', '16']], dtype='<U2')

[문제3]
06_data2.txt 파일을 읽어와서 변수 arr2에 저장하고 출력해 봅시다.

In [33]:
arr2 = np.loadtxt('C:/Study/Study_Python2/data/06_data2.txt', delimiter=',' ,dtype=np.int8)
arr2

array([[ 1, 15, 14,  4],
       [12,  6,  7,  9],
       [ 8, 10, 11,  5],
       [13,  3,  2, 16]], dtype=int8)

파일 ex1_지역별 전기요금데이터 현황

In [40]:
data = np.loadtxt('C:/Study/Study_Python2/data/ex1_지역별전기요금.csv', delimiter=',', dtype=int)
print(data[:5,:]) # 상위 5개 데이터 출력

[[      1  565082     273   27177]
 [      2 2827233     444   45111]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      5  380425     391   38020]]


02. 데이터 확인하기

In [42]:
# 데이터의 모양 확인
print(data.shape)

(17, 4)


In [46]:
# 중복 지역 확인
print(np.unique(data[:,0]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [52]:
# 데이터의 크기순 정렬(argsort 사용)  # sort는 행렬을 다 섞어버림.
print(data[:,1].argsort())

[ 9 14 10  4  6  0 16 13  5 12 11 15  7  3  2  8  1]


In [48]:
# fancy index
print(data[data[:,1].argsort()])
# print(data[data[:,1].argsort()[::-1]])  #내림차순

[[     10   49394     580   57091]
 [     15  258605     221   22180]
 [     11  323151     353   35470]
 [      5  380425     391   38020]
 [      7  425659     344   32331]
 [      1  565082     273   27177]
 [     17  584500     268   26899]
 [     14  634696     285   28556]
 [      6  668623     364   35245]
 [     13  726699     249   25120]
 [     12  734723     398   40049]
 [     16  742285     282   27901]
 [      8  947300     366   36274]
 [      4 1131034     230   22436]
 [      3 1144913     289   29043]
 [      9 2737725     361   36569]
 [      2 2827233     444   45111]]


03. 데이터 통계

In [53]:
# 전국 대상 가구수의 합
print(np.sum(data[:,1]))

14882047


In [55]:
# 가구당 평균 전력 사용량의 전국 평균값
print(round(data[:,2].mean(),2))  # data[:,2].mean()

335.18


In [62]:
# 무식하게 평균 구하기
e_sum = np.sum(data[:,2])
e_sum

n_rows = data.shape[0]
n_rows

print('가구당 평균 전력 사용랴의 전국 평균값 :', round(e_sum/n_rows,2))

가구당 평균 전력 사용랴의 전국 평균값 : 335.18


In [64]:
# 가구당 평균 전력 사용량이 평균 이상인 지역과 대상 가구수 추출
avg_ = data[:,2].mean() #가구당 평균 전력 사용량의 전국 평균
print(data[data[:,2]>avg_, 0:2])

[[      2 2827233]
 [      5  380425]
 [      6  668623]
 [      7  425659]
 [      8  947300]
 [      9 2737725]
 [     10   49394]
 [     11  323151]
 [     12  734723]]


파일 ex2_전년대비_시도별_교통사망사고 데이터 현황

[문제1]
위 파일을 읽어보고 상위 3개의 (발생년도, 발생건수, 구성비)의 데이터를 추출해 봅시다.

In [117]:
data1 = np.loadtxt('C:/Study/Study_Python2/data/ex2_전년대비_시도별_교통사망사고.csv', delimiter=',', dtype=float)
print(data1[:3,[0,2,3]])

[[2014.   218.     4.8]
 [2014.   872.    19. ]
 [2014.   401.     8.7]]


[문제2]
위 데이터에서 부산에서 발생한 교통사망사고 모든 현황을 추출해 봅시다.

In [119]:
print(data1[7,:])

print(data1[data1[:,1]==8])

[2014.     8.   163.     3.6  -47.   -22.4]
[[2014.     8.   163.     3.6  -47.   -22.4]]


[문제3]
위 데이터에서 전국 사고 발생건수의 합계와 전국 평균을 계산해 봅시다.

In [81]:
print('전국 사고 발생건수의 전국 합계 :', np.sum(data1[:,2]))   # data1[:,2].sum()
print('전국 사고 발생건수의 전국 평균 :', round(data1[:,2].mean(),2))

전국 사고 발생건수의 전국 합계 : 4583
전국 사고 발생건수의 전국 평균 : 269.59


[문제4]
위 데이터에서 교통사고 증감수가 가장 큰 지역의 모든 현황을 추출해 봅시다.

In [101]:
data1[:,4].argsort() 

# 기본이 오름차순

array([ 7,  1,  2,  3, 13, 12, 16, 10, 14,  0, 11, 15,  4,  9,  6,  8,  5],
      dtype=int64)

In [112]:
# 내가 한 답
print(data1[data1[:,4].argsort()[::-1][0]])

[2014    6  182    4   19   11]


In [123]:
max(data1[:,4])
print(data1[data1[:,4]==max(data1[:,4])])

[[2014.     6.   182.     4.    19.    11.7]]


In [124]:
print(data1[np.argmax(data1[:,4])])

[2014.     6.   182.     4.    19.    11.7]


[문제5]
위 데이터에서 교통사고 증감률이 가장 작은 지역의 모든 현황을 추출해 봅시다.

In [127]:
# 내가 한 답
print(data1[data1[:,5].argsort()[0]])


[2014.     8.   163.     3.6  -47.   -22.4]


In [128]:
min(data1[:,5])
print(data1[data1[:,5]==min(data1[:,5])])

[[2014.     8.   163.     3.6  -47.   -22.4]]


In [130]:
print(data1[np.argmin(data1[:,5])])

[2014.     8.   163.     3.6  -47.   -22.4]


[문제6]
위 데이터에서 사고 발생 건수가 400건 이상인 곳의 지역과 교통사고 발생건수, 증감수, 증감률을 추출해 봅시다.

In [131]:
print(data1[data1[:,2]>=400][:,[1,2,4,5]])


[[  2.  872.  -45.   -4.9]
 [  3.  401.  -45.  -10.1]
 [  4.  464.  -41.   -8.1]
 [ 13.  400.  -35.   -8. ]]
