### numpy 모듈 호출

In [3]:
import numpy as np

In [3]:
a = np.array(1)
a

array(1)

### 배열생성

In [4]:
ndarr_1 = np.array([1,2,3])
print(ndarr_1)

[1 2 3]


In [5]:
ndarr_2 = np.array([1,2.0,3])
print(ndarr_2)

# 1.은 0이 생략되어있는 형태

[1. 2. 3.]


In [6]:
ndarr_3 = np.array([1,2.0,'3'])
print(ndarr_3)

# 리스트 안의 모든 값이 문자로 바뀜

['1' '2.0' '3']


### 배열의 정보확인
자료형 확인 속성
ndarray.dtype

In [7]:
print(ndarr_1.dtype)
print(ndarr_2.dtype)
print(ndarr_3.dtype)

int32
float64
<U32


In [9]:
print(np.array(1 +2j).dtype)
print(np.array(print).dtype)

complex128
object


### 자료형 지정
dtype 속성을 사용하여 자료형 지정

In [10]:
dtype1 = np.array([1,2,3], dtype=np.int8)
print(dtype1.dtype)


int8


In [12]:
dtype2 = np.array([1,2,3], dtype=float)
print(dtype2.dtype)


float64


In [13]:
dtype3 = np.array([1,2,3], dtype=str)
print(dtype3.dtype)


<U1


In [14]:
dtype4 = np.array([1,2,1,'3'], dtype=int)
print(dtype4)
print(dtype4.dtype)


[1 2 1 3]
int32


In [47]:
dtype5 = np.array([1,'data',1, print], dtype=float)
print(dtype5)
print(dtype5.dtype)


ValueError: could not convert string to float: 'data'

### 배열의 정보확인
배열 크기확인
ndarray.shape

In [15]:
print(ndarr_1.shape)

(3,)


배열차원 확인
ndarray.ndim

In [17]:
print(ndarr_1.ndim)

1


### 배열생성
1차원 배열생성

In [18]:
vector = np.array([1,2,3])
print(vector)
print(vector.shape)
print(vector.ndim)
print(vector.dtype)

[1 2 3]
(3,)
1
int32


2차원 배열생성

In [21]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.shape)
print(matrix.ndim)
print(matrix.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


3차원 배열생성

In [22]:
tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor)
print(tensor.shape)
print(tensor.ndim)
print(tensor.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3
int32


### 배열의 정보확인
배열 요소의 개수 확인
ndarray.size

In [24]:
print(vector.size)
print(matrix.size)
print(tensor.size)

3
6
12


### 배열생성
[문제1] 위와 같은 배열을 생성하고 차원, 크기, 모양을 알아내시오

In [29]:
arr = np.array([[1,2,3],[2,4,6],[3,6,9]])
print(arr.ndim)
print(arr.size)
print(arr.shape)

2
9
(3, 3)


### 자료형변환(리스트)
리스트 -> ndarray 변환

In [30]:
list1=[1,2,3]
arr1 = np.array(list1)
print(arr1)

[1 2 3]


ndarray 변환 -> 리스트

In [3]:
arr2 = np.array([1,2,3])
list2 = list(arr2)
print(list2)

[1, 2, 3]


2차원 리스트 변환

In [33]:
list3 = [[1,2,3,],[4,5,6]]
arr3 = np.array(list3)
print(arr3)

[[1 2 3]
 [4 5 6]]


주의해야할 점 - shape이 다른 리스트인 경우

In [34]:
list4 = [[1,2,3,4],[5,6,7]]
arr4 = np.array(list4)
print(arr4)

[list([1, 2, 3, 4]) list([5, 6, 7])]


C:\Users\admin\AppData\Local\Temp\ipykernel_10316\2158651982.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr4 = np.array(list4)


### 자료형변환(튜플)
튜플 -> ndarray 변환

In [37]:
tuple1 = (1,2,3)
arr = np.array(tuple1)
print(arr)

[1 2 3]


ndarray => 튜플 변환

In [38]:
arr2 = np.array([1,2,3])
tuple2 = tuple(arr2)
print(tuple2)

(1, 2, 3)


### 자료형변환(세트, 딕셔너리)
세트변환

In [40]:
set1 = {1,2,3}
arr = np.array(set1)
print(arr)

print(arr.size)

{1, 2, 3}
1


딕셔너리 변환

In [42]:
dict1 = {'a':1, 'b':2, 'c':3}
arr = np.array(dict1)
print(arr)

print(arr.size)

{'a': 1, 'b': 2, 'c': 3}
1


### 배열 인덱싱
리스트 인덱싱과 유사
- ndarray[col]
- ndarray[row][col]
- ndarray[rank][row][col]

In [44]:
list_ = [[[1,2],[3,4]],[[5,6],[7,8]]]
# 1 가져오기
print(list_[0][0][0])
# 4 가져오기
print(list_[0][1][1])
# 7 가져오기
print(list_[1][1][0])



1
4
7


배열인덱싱

In [1]:
arr_ = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
# 1 가져오기
print(arr_[0][0][0])
# 4 가져오기
print(arr_[0][1][1])
# 7 가져오기
print(arr_[1][1][0])

NameError: name 'np' is not defined

ndarray의 인덱싱
- array[row, col]
- array[rank, row, col]

In [49]:
arr_ = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
# 1 가져오기
print(arr_[0,0,0])
# 4 가져오기
print(arr_[0,1,1])
# 7 가져오기
print(arr_[1,1,0])

1
4
7


In [50]:
arr_1 = np.array([[1,2],[3,4],[5,6]])  # 2x3 형태의 2차원 배열

# 0행 가져와 2차원 배열 만들기
print(arr_1[[0]])

# 0, 2행 가져와 2차원 배열 만들기
print(arr_1[[0,2]])

# 다음 결과는?
print(arr_1[[0,1,2],[0,1,0]]) # row1,col1 = 0,0 / row2,col2 = 1,1 / row3,col3 =2,0

# 같은 위치 데이터 여러 번 사용가능
print(arr_1[[0,0],[1,1]])


[[1 2]]
[[1 2]
 [5 6]]
[1 4 5]
[2 2]


In [51]:
arr_2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

# 두개의 1차원 배열 만들기
b = np.array([0,1,2,3])
c = np.array([0,2,0,1])

# 다음 코드의 실행 결과는?
print(arr_2[b,c])

[ 1  6  7 11]


Boolean 인덱싱

In [52]:
# 기본데이터
arr = np.array([1,2,3,4,5])

# True, False
print(arr[[True,False,True,True,False]])

# 조건
print(arr[arr >=3])

[1 3 4]
[3 4 5]


[문제2]
score = np.array([[78,91,84,89,93,65],[82,87,96,79,91,73]])
위와 같은 2x6 형태의 2차원 배열을 생성하고 각각 0행과 1행에서 90이상인 숫자를 추출해봅시다.

In [57]:
score = np.array([[78,91,84,89,93,65],[82,87,96,79,91,73]])

print(score[0][score[0]>=90])
print(score[1][score[1]>=90])


[91 93]
[96 91]


### 배열 슬라이싱
ndarray의 슬라이싱
- 행과 열 부분을 나눠서 슬라이싱 가능
- 다차원 배열의 부분 데이터를 추출할 때 유용

In [13]:
# 기본데이터 4x5 형태의 2차원 배열
matrix = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20]])

## ndarray의 슬라이싱
# 0열 전체 슬라이싱
print(matrix[:,0])

# 0열 전체 슬라이싱 (2차원유지)
print(matrix[:,:1])

[ 1  6 11 16]
[[ 1]
 [ 6]
 [11]
 [16]]


In [12]:
# 1행 전체 슬라이싱
print(matrix[1,:])

# 1행 전체 슬라이싱
print(matrix[1])  # rank > row > col 순으로 :(클론) 생략가능

# 1행 전체 슬라이싱(2차원 유지)
print(matrix[1:2,:])  #or print(matrix[[1]])

[ 6  7  8  9 10]
[ 6  7  8  9 10]
[[ 6  7  8  9 10]]


In [11]:
# 3~4열 전체 슬라이싱
print(matrix[:,3:])

# 0행, 1~3열 슬라이싱
print(matrix[0,1:-1])

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]
[2 3 4]


In [17]:
# 2~3행, 2~4열 슬라이싱
print(matrix[-2:,-3:])

# 1~2행, 1~2열 슬라이싱
print(matrix[1:-1,1:3])

[[13 14 15]
 [18 19 20]]
[[ 7  8]
 [12 13]]


### 배열 인덱싱, 슬라이싱 복합

### 

In [19]:
# 1, 3행, 2~4열 슬라이싱
print(matrix[[1,3],2:])

# 1~2행, 1, 3열 슬라이싱
print(matrix[1:-1,[1,3]])

[[ 8  9 10]
 [18 19 20]]
[[ 7  9]
 [12 14]]


[문제3]
tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
위와 같은 2x2x3 형태의 3차원 배열을 생성하고 인덱싱을 사용해 [10 2 6] 배열을 추출해봅시다

In [24]:
tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor[[1,0,0],[1,0,1],[0,1,2]])

[10  2  6]


[문제3]
문제 3의 tensor 배열에서 인덱싱, 슬라이싱을 사용해 [[1 2]
                                                    [4 5]] 배열과 [9 12] 배열을 추출해봅시다

In [44]:
print(tensor[0,:,:2])
print(tensor[1,:,2])
print(tensor[1,:,-1:])

[[1 2]
 [4 5]]
[ 9 12]
[[ 9]
 [12]]
