In [7]:
import numpy as np

### Numpy활용
Reshape
- 배열의 shape을 변형해주는 함수
- 배열의 요소 개수를 유지하며 형태만 변경
- 변형 전 size와 변형 후 size가 동일해야 함

array.reshape(size)

In [7]:
arr = np.array([[1,2,3],[4,5,6]])  # 2x3 형태의 2차원 배열
print(arr.reshape(3,2)) # 3x2 형태의 배열로 변형

# 6x1 배열로 변형
print(arr.reshape(6,1))
# 1x6 배열로 변형
print(arr.reshape(1,6))

[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]


In [8]:
# 3x1x2 배열로 변형
print(arr.reshape(3,1,2))
# ?x2 배열로 변형 
print(arr.reshape(-1,2))

[[[1 2]]

 [[3 4]]

 [[5 6]]]
[[1 2]
 [3 4]
 [5 6]]


[문제1]
range() 함수를 사용해 1부터 36까지의 숫자가 나열된 tensor배열을 생성하고 (3,3,4)형태의 3차원 배열로 변형해봅시다.

In [17]:
tensor = np.array(range(1,37))  #shape(3,3,4)
print(tensor.reshape(3,3,4))


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


[문제2]
tensor 배열을 2차원 배열로 변형시켜봅니다. *열의 개수는 9

In [18]:
print(tensor.reshape(-1,9))

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]]


### Flatten
다차원 배열을 1차원배열로 변형

In [21]:
# shape(2,3) -> shape(6,)
print(arr.flatten())

# shape(1,6) -> shape(6,)
print(arr.reshape(1,6).flatten())

# shape(3,1,2) -> shape(6,)
print(arr.reshape(3,1,2).flatten())

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


### Arange
- range 함수와 비슷한기능
- 값의 범위를 지정하여 값이 채워져 있는 배열을 생성
- 특정한 규칙에 따라 증가하는 값을 넣는 것도 가능

np.arange(size)

In [22]:
print(np.arange(30))  # np.array(range(30))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


간격지정 : np.arange(start, end, step)

In [24]:
print(np.arange(0,10,2))

print(np.arange(0,2,0.2))

[0 2 4 6 8]
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8]


### Arange + Reshape
배열 요소를 순서대로 가지는 다차원배열 생성 가능

arange + reshape

In [29]:
print(np.arange(1,26).reshape(5,5))

print(np.arange(0,6,0.2).reshape(3,2,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[[0.  0.2 0.4 0.6 0.8]
  [1.  1.2 1.4 1.6 1.8]]

 [[2.  2.2 2.4 2.6 2.8]
  [3.  3.2 3.4 3.6 3.8]]

 [[4.  4.2 4.4 4.6 4.8]
  [5.  5.2 5.4 5.6 5.8]]]


[문제3] 
arange, reshape 함수를 사용해 100부터 190까지의 숫자가 10 간격으로 나열된 배열을 생성하고 (2,5) 형태의 2차원 배열로 변형해봅시다.

In [30]:
print(np.arange(100,191,10).reshape(2,5))

[[100 110 120 130 140]
 [150 160 170 180 190]]


[문제4] 
arange, reshape 함수를 사용해 -2부터 2까지의 숫자가 0.5 간격으로 나열된 배열을 생성하고 3차원 배열로 변형해봅시다.

In [36]:
print(np.arange(-2,2.1,0.5).reshape(1,3,3))  # 괄호갯수로 차원 확인가능(괄호가 3개면 3차원)

[[[-2.  -1.5 -1. ]
  [-0.5  0.   0.5]
  [ 1.   1.5  2. ]]]


### Zeros
- 0으로 채워진 배열생성
- shape 지정이 가능

np.zeros(shape,dtype)

In [42]:
print(np.zeros(shape=(5,), dtype=np.int8))

print(np.zeros((5), int))

print(np.zeros((2,3)))  # 기본 디폴트값 float

[0 0 0 0 0]
[0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]]


### Ones
- 1으로 채워진 배열생성
- shape 지정이 가능

np.ones(shape,dtype)

In [34]:
print(np.ones(shape=(5,),dtype=np.int8))
print(np.ones((5),int))
print(np.ones((2,3)))

[1 1 1 1 1]
[1 1 1 1 1]
[[1. 1. 1.]
 [1. 1. 1.]]


### Empty
- shape만 주어지고 비어있는 배열 생성
- 배열을 생성만 하고 값을 주지않아 메모리에 저장되어 있던 기존값이 저장될수 있음

np.empty(shape, dtype)

In [47]:
print(np.empty(shape=(10,),dtype=np.int32))

print(np.empty(shape=(2,5),dtype=np.int8))

[100 110 120 130 140 150 160 170 180 190]
[[1 1 1 1 0]
 [1 1 1 1 1]]


### Zeros_like / Ones_like / Empty_like
- 입력받은 배열과 같은 shape,dtype의 배열 생성

np.zeros_like(ndarray)

In [2]:
matrix = np.arange(24).reshape(4,6)
print(np.zeros_like(matrix))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


np.ones_like(ndarray)

In [3]:
matrix = np.arange(-2,2,0.2).reshape(2,10)

print(np.ones_like(matrix))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


np.empty_like(ndarray)

In [4]:
matrix = np.arange(30).reshape(5,6)
print(np.empty_like(matrix))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


### Identity
- 단위행렬 - 주대각선의 값이 1이고 나머지는 0인 정사각 행렬

np.identity(size,dtype)

In [5]:
print(np.identity(5, dtype=np.str_))

print(np.identity(5,dtype=np.int8))

print(np.identity(2))

[['1' '' '' '' '']
 ['' '1' '' '' '']
 ['' '' '1' '' '']
 ['' '' '' '1' '']
 ['' '' '' '' '1']]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[1. 0.]
 [0. 1.]]


### Eye
- 대각선이 1로 채워지는 행렬
- 대각선의 시작 위치 지정 가능

np.eye(size, M, k, dtype)
- k : 대각선의 시작 위치를 입력 받은 수 만큼 오른쪽으로 이동
- M : 보여지는 열의 개수를 지정

In [6]:
print(np.eye(5,dtype=np.int8))

print(np.eye(5, k=2))

print(np.eye(5, M=10, k=-1))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


### Full
입력값으로 채워지는 행렬

np.full((shape), value)

In [9]:
print(np.full((2,5), 5))

print(np.full((5,4),'a'))

[[5 5 5 5 5]
 [5 5 5 5 5]]
[['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']]


In [12]:
np.ones((3,3)) * 3

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [13]:
np.full((3,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

### Random.randint
주어진 법위 안에 랜덤한 값을 뽑는 함수

np.random.randint(range)

In [18]:
# 0~5 까지의 정수 중 하나 뽑기
print(np.random.randint(6))

# 1~19 까지의 정수 중 하나 뽑기
print(np.random.randint(1,20))

5
7


### Randon.rand
- 랜덤한 값으로 채워지는 배열
- 표준정규분포 난수를 shape 형태의 배열로 생성
- 0~1 사이의 값을 가짐

np.random.rand(shape)

In [30]:
print(np.random.rand(3))

print(np.random.rand(3,2))

[0.39363512 0.12370424 0.29630065]
[[0.51302626 0.92377433]
 [0.97114998 0.48810052]
 [0.00616881 0.55799061]]


### Random.randn
- 랜덤한 값으로 채워지는 배열
- 평균 0, 표준편차1의 가우시안 표준정규분포 난수를 shape 형태의 배열로 생성

np.random.randn(shape)

In [32]:
# 음수도 나올 수 있음

print(np.random.randn(3))

print(np.random.randn(3,2))

[-1.98135344 -0.48573279 -0.39773372]
[[ 0.05533042 -1.29710792]
 [ 3.01309361  0.63214819]
 [ 0.05007916  0.22669735]]


### 연산함수
- 배열의 요소값들을 이용하여 연산을 할 수 있게 해주는 함수

### 합(sum)
- 요소들의 합을 구해주는 합수
- ndarray.sum()

In [33]:
# 2차원 배열 합

matrix = np.arange(1,7).reshape(2,3)
print(matrix.sum())

21


In [34]:
print(matrix.sum(axis=0)) # 행끼리 더하기(위 아래)
print(matrix.sum(axis=1)) # 열끼리 더하기 (좌 우)

[5 7 9]
[ 6 15]


In [35]:
# 3차원 배열 합
tensor = np.arange(1,19).reshape(3,2,3)
print(tensor)    
print(tensor.sum())

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
171


In [36]:
print(tensor.sum(axis=0))    # np.sum(tensor)
print(tensor.sum(axis=1))
print(tensor.sum(axis=2))


[[21 24 27]
 [30 33 36]]
[[ 5  7  9]
 [17 19 21]
 [29 31 33]]
[[ 6 15]
 [24 33]
 [42 51]]


### 평균(mean)
- 합과 동일

2차원 배열 평균

In [38]:
print(matrix.mean())
print(matrix.mean(axis=0))
print(matrix.mean(axis=1))

3.5
[2.5 3.5 4.5]
[2. 5.]


### 표준편차(std)
- 합, 평균과 동일

2차원 배열 표준 편차

In [40]:
print(matrix.std())  # 전체 표준편차
print(matrix.std(axis=0))  # 행끼리 표준 편차 (위 아래)
print(matrix.std(axis=1))  # 열끼리 표준 편차 (좌 우)

1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


### 그 외 수학 연산자

In [44]:
# 지수
print(np.exp(matrix))

# 로그
print(np.log(matrix))

# 제곱근
print(np.sqrt(matrix))

# 삼각함수(sin)
print(np.sin(matrix))

# 삼각함수(cos)
print(np.cos(matrix))

# 삼각함수(tan)
print(np.tan(matrix))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]


### 배열 정렬(Sort)
1차원 배열 정렬

In [51]:
# randint를 사용하여 1~100 숫자 중 5개를 뽑아 배열 생성
vector = np.array([np.random.randint(1,100)
                   for n in range(5)])
print(vector)

print(np.sort(vector))   # 오름차순으로 정렬
print(np.sort(vector)[::-1])   # 내림차순으로 정렬


[68  4 37 98 75]
[ 4 37 68 75 98]
[98 75 68 37  4]


2차원 배열정렬

In [56]:
# randint를 사용하여 1~100 숫자 중 5개를 뽑아 배열 생성
matrix = np.array([np.random.randint(1,100)
                   for n in range(20)]).reshape(4,5)

print(matrix)

print(np.sort(matrix)) # 열기준으로 정렬, axis=1
print(np.sort(matrix, axis=0)) # 행기준으로 정렬



[[81  1 15 87 24]
 [87 94 44 53 13]
 [89 96 76 60 76]
 [49 77 79 83 97]]
[[ 1 15 24 81 87]
 [13 44 53 87 94]
 [60 76 76 89 96]
 [49 77 79 83 97]]
[[49  1 15 53 13]
 [81 77 44 60 24]
 [87 94 76 83 76]
 [89 96 79 87 97]]


### 배열합치기(Vstack)
- 2개 이상의 배열을 수직으로 합체

np.vstack([arr1,arr2])

In [57]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

print(np.vstack([vector1,vector2]))

[[1 2 3]
 [4 5 6]]


### 배열합치기(Hstack)
- 2개 이상의 배열을 수평으로 합체

np.hstack([arr1,arr2])

In [58]:
vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)

print(np.hstack([vector1,vector2]))

[[1 4]
 [2 5]
 [3 6]]


### 배열합치기(Concatenate)
- 2개 이상의 배열을 수직, 수평으로 합체

np.concatenate(arr1, arr2, axis)

In [36]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

print(np.concatenate([vector1,vector2],axis=0))



[1 2 3 4 5 6]


In [35]:
vector1 = np.array([1,2,3,]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)

print(np.concatenate([vector1,vector2],axis=1))


[[1 4]
 [2 5]
 [3 6]]


In [9]:
matrix1 = np.arange(1,5).reshape(2,2)
matrix2 = np.arange(5,9).reshape(2,2)

print(np.concatenate([matrix1, matrix2],axis=0))



[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [10]:
matrix1 = np.arange(1,5).reshape(2,2)
matrix2 = np.arange(5,9).reshape(2,2)

print(np.concatenate([matrix1, matrix2],axis=1))


[[1 2 5 6]
 [3 4 7 8]]


### 행/열 바꾸기(transpose)
- 행과 열을 뒤집어 주는 함수

    - ndarray.tranpose()
    - ndarray.T

In [15]:
matrix3 = np.array([[5,6]])
print(matrix3)

print(matrix3.transpose())
print(matrix3.T)

[[5 6]]
[[5]
 [6]]
[[5]
 [6]]


### Transpose + Concatenate
- 형태를 바꿔 서로 결합할 수 없는 배열을 합칠 수 있다.

In [17]:
print(np.concatenate([matrix1, matrix3]))

print(np.concatenate([matrix1, matrix3], axis =1))

[[1 2]
 [3 4]
 [5 6]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [18]:
print(np.concatenate([matrix1, matrix3.T], axis = 1))

[[1 2 5]
 [3 4 6]]


### 인덱스 반환 함수
최대값, 최소값의 인덱스

argmax, argmin 

In [21]:
a = np.arange(1,11).reshape(2,5)
print(a)
print(np.argmax(a), np.argmin(a))

print(np.argmax(a,axis=0))   # [11111] 위치를 말하는 것! 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
9 0
[1 1 1 1 1]


In [25]:
b = np.array([[1,2,3,4],[2,3,4,1],[3,4,1,2]])
print(b)
print(np.argmax(b, axis=1))
print(np.argmax(b, axis=0))


[[1 2 3 4]
 [2 3 4 1]
 [3 4 1 2]]
[3 2 1]
[2 2 1 0]


### 배열 인덱싱(Rancy Index)
인덱스의 값을 가지는 배열을 통해 인덱싱

In [27]:
a = np.arange(1,11)
b = np.array([3,4,5,6])

print(a)
print(b)
print(a[b])

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5 6]
[4 5 6 7]


- 인덱스 반환 함수 + fancy index

In [28]:
a = np.arange(10,20)
b = np.argmax(a)

print(a)
print(b)

print(a[b])

[10 11 12 13 14 15 16 17 18 19]
9
19
